// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server/static-srv/proto/common/common.proto

/*
Package go_micro_srv_static is a generated protocol buffer package.

It is generated from these files:
	server/static-srv/proto/common/common.proto

It has these top-level messages:
	Pending
	PendingResponse
	DayItems
	DayItem
	AccountConfirmationMessage
	CommonFilter
*/
package go_micro_srv_static

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/any"
import go_micro_srv_user "server/user-srv/proto/user"
import go_micro_srv_todo "server/todo-srv/proto/todo"
import go_micro_srv_organisation "server/organisation-srv/proto/organisation"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Pending struct {
	Id         string                  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	OrgId      string                  `protobuf:"bytes,2,opt,name=org_id,json=orgId" json:"org_id,omitempty"`
	Created    int64                   `protobuf:"varint,5,opt,name=created" json:"created,omitempty"`
	SharedBy   *go_micro_srv_user.User `protobuf:"bytes,6,opt,name=shared_by,json=sharedBy" json:"shared_by,omitempty"`
	SharedWith *go_micro_srv_user.User `protobuf:"bytes,7,opt,name=shared_with,json=sharedWith" json:"shared_with,omitempty"`
	Item       *google_protobuf.Any    `protobuf:"bytes,8,opt,name=item" json:"item,omitempty"`
	Updated    int64                   `protobuf:"varint,9,opt,name=updated" json:"updated,omitempty"`
}

func (m *Pending) Reset()                    { *m = Pending{} }
func (m *Pending) String() string            { return proto.CompactTextString(m) }
func (*Pending) ProtoMessage()               {}
func (*Pending) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Pending) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Pending) GetOrgId() string {
	if m != nil {
		return m.OrgId
	}
	return ""
}

func (m *Pending) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Pending) GetSharedBy() *go_micro_srv_user.User {
	if m != nil {
		return m.SharedBy
	}
	return nil
}

func (m *Pending) GetSharedWith() *go_micro_srv_user.User {
	if m != nil {
		return m.SharedWith
	}
	return nil
}

func (m *Pending) GetItem() *google_protobuf.Any {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *Pending) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

type PendingResponse struct {
	Id           string                  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	OrgId        string                  `protobuf:"bytes,2,opt,name=org_id,json=orgId" json:"org_id,omitempty"`
	Image        string                  `protobuf:"bytes,3,opt,name=image" json:"image,omitempty"`
	Title        string                  `protobuf:"bytes,4,opt,name=title" json:"title,omitempty"`
	Created      int64                   `protobuf:"varint,5,opt,name=created" json:"created,omitempty"`
	SharedWithId string                  `protobuf:"bytes,6,opt,name=shared_with_id,json=sharedWithId" json:"shared_with_id,omitempty"`
	Summary      string                  `protobuf:"bytes,7,opt,name=summary" json:"summary,omitempty"`
	SharedBy     *go_micro_srv_user.User `protobuf:"bytes,8,opt,name=shared_by,json=sharedBy" json:"shared_by,omitempty"`
	Item         *google_protobuf.Any    `protobuf:"bytes,9,opt,name=item" json:"item,omitempty"`
	Duration     string                  `protobuf:"bytes,10,opt,name=duration" json:"duration,omitempty"`
	Count        int32                   `protobuf:"varint,11,opt,name=count" json:"count,omitempty"`
}

func (m *PendingResponse) Reset()                    { *m = PendingResponse{} }
func (m *PendingResponse) String() string            { return proto.CompactTextString(m) }
func (*PendingResponse) ProtoMessage()               {}
func (*PendingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PendingResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PendingResponse) GetOrgId() string {
	if m != nil {
		return m.OrgId
	}
	return ""
}

func (m *PendingResponse) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *PendingResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *PendingResponse) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *PendingResponse) GetSharedWithId() string {
	if m != nil {
		return m.SharedWithId
	}
	return ""
}

func (m *PendingResponse) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *PendingResponse) GetSharedBy() *go_micro_srv_user.User {
	if m != nil {
		return m.SharedBy
	}
	return nil
}

func (m *PendingResponse) GetItem() *google_protobuf.Any {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *PendingResponse) GetDuration() string {
	if m != nil {
		return m.Duration
	}
	return ""
}

func (m *PendingResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type DayItems struct {
	Items []*DayItem `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
}

func (m *DayItems) Reset()                    { *m = DayItems{} }
func (m *DayItems) String() string            { return proto.CompactTextString(m) }
func (*DayItems) ProtoMessage()               {}
func (*DayItems) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DayItems) GetItems() []*DayItem {
	if m != nil {
		return m.Items
	}
	return nil
}

type DayItem struct {
	Id               string                  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	ContentId        string                  `protobuf:"bytes,2,opt,name=content_id,json=contentId" json:"content_id,omitempty"`
	CategoryId       string                  `protobuf:"bytes,3,opt,name=category_id,json=categoryId" json:"category_id,omitempty"`
	CategoryIconSlug string                  `protobuf:"bytes,4,opt,name=category_icon_slug,json=categoryIconSlug" json:"category_icon_slug,omitempty"`
	CategoryName     string                  `protobuf:"bytes,5,opt,name=category_name,json=categoryName" json:"category_name,omitempty"`
	ContentTitle     string                  `protobuf:"bytes,6,opt,name=content_title,json=contentTitle" json:"content_title,omitempty"`
	ContentPicUrl    string                  `protobuf:"bytes,7,opt,name=content_pic_url,json=contentPicUrl" json:"content_pic_url,omitempty"`
	Primary          bool                    `protobuf:"varint,8,opt,name=primary" json:"primary,omitempty"`
	Time             string                  `protobuf:"bytes,9,opt,name=time" json:"time,omitempty"`
	Pre              *go_micro_srv_todo.Todo `protobuf:"bytes,10,opt,name=pre" json:"pre,omitempty"`
	Post             *go_micro_srv_todo.Todo `protobuf:"bytes,11,opt,name=post" json:"post,omitempty"`
	Options          []*DayItem              `protobuf:"bytes,12,rep,name=options" json:"options,omitempty"`
}

func (m *DayItem) Reset()                    { *m = DayItem{} }
func (m *DayItem) String() string            { return proto.CompactTextString(m) }
func (*DayItem) ProtoMessage()               {}
func (*DayItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *DayItem) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DayItem) GetContentId() string {
	if m != nil {
		return m.ContentId
	}
	return ""
}

func (m *DayItem) GetCategoryId() string {
	if m != nil {
		return m.CategoryId
	}
	return ""
}

func (m *DayItem) GetCategoryIconSlug() string {
	if m != nil {
		return m.CategoryIconSlug
	}
	return ""
}

func (m *DayItem) GetCategoryName() string {
	if m != nil {
		return m.CategoryName
	}
	return ""
}

func (m *DayItem) GetContentTitle() string {
	if m != nil {
		return m.ContentTitle
	}
	return ""
}

func (m *DayItem) GetContentPicUrl() string {
	if m != nil {
		return m.ContentPicUrl
	}
	return ""
}

func (m *DayItem) GetPrimary() bool {
	if m != nil {
		return m.Primary
	}
	return false
}

func (m *DayItem) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *DayItem) GetPre() *go_micro_srv_todo.Todo {
	if m != nil {
		return m.Pre
	}
	return nil
}

func (m *DayItem) GetPost() *go_micro_srv_todo.Todo {
	if m != nil {
		return m.Post
	}
	return nil
}

func (m *DayItem) GetOptions() []*DayItem {
	if m != nil {
		return m.Options
	}
	return nil
}

type AccountConfirmationMessage struct {
	VerificationToken string                                  `protobuf:"bytes,1,opt,name=verification_token,json=verificationToken" json:"verification_token,omitempty"`
	User              *go_micro_srv_user.User                 `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
	Organisation      *go_micro_srv_organisation.Organisation `protobuf:"bytes,3,opt,name=organisation" json:"organisation,omitempty"`
}

func (m *AccountConfirmationMessage) Reset()                    { *m = AccountConfirmationMessage{} }
func (m *AccountConfirmationMessage) String() string            { return proto.CompactTextString(m) }
func (*AccountConfirmationMessage) ProtoMessage()               {}
func (*AccountConfirmationMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *AccountConfirmationMessage) GetVerificationToken() string {
	if m != nil {
		return m.VerificationToken
	}
	return ""
}

func (m *AccountConfirmationMessage) GetUser() *go_micro_srv_user.User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *AccountConfirmationMessage) GetOrganisation() *go_micro_srv_organisation.Organisation {
	if m != nil {
		return m.Organisation
	}
	return nil
}

type CommonFilter struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *CommonFilter) Reset()                    { *m = CommonFilter{} }
func (m *CommonFilter) String() string            { return proto.CompactTextString(m) }
func (*CommonFilter) ProtoMessage()               {}
func (*CommonFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CommonFilter) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*Pending)(nil), "go.micro.srv.static.Pending")
	proto.RegisterType((*PendingResponse)(nil), "go.micro.srv.static.PendingResponse")
	proto.RegisterType((*DayItems)(nil), "go.micro.srv.static.DayItems")
	proto.RegisterType((*DayItem)(nil), "go.micro.srv.static.DayItem")
	proto.RegisterType((*AccountConfirmationMessage)(nil), "go.micro.srv.static.AccountConfirmationMessage")
	proto.RegisterType((*CommonFilter)(nil), "go.micro.srv.static.CommonFilter")
}

func init() { proto.RegisterFile("server/static-srv/proto/common/common.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 699 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x5d, 0x6f, 0xd3, 0x48,
	0x14, 0x95, 0xf3, 0xed, 0x9b, 0x6c, 0xbb, 0x3b, 0xdb, 0xd5, 0x7a, 0xa3, 0xfd, 0x88, 0xb2, 0x7c,
	0x04, 0x95, 0x3a, 0x52, 0x40, 0x88, 0x17, 0x90, 0x4a, 0x11, 0x52, 0x84, 0x80, 0xca, 0xb4, 0xe2,
	0x31, 0x72, 0xed, 0xa9, 0x3b, 0x22, 0x9e, 0xb1, 0x66, 0xc6, 0x41, 0xf9, 0x65, 0xfc, 0x02, 0xde,
	0xf9, 0x45, 0x08, 0xcd, 0x9d, 0x71, 0xeb, 0xb4, 0x28, 0xf4, 0xc5, 0xc9, 0x39, 0x3e, 0x77, 0x7c,
	0xe7, 0x9c, 0x3b, 0x03, 0xfb, 0x8a, 0xca, 0x15, 0x95, 0x53, 0xa5, 0x63, 0xcd, 0x92, 0x03, 0x25,
	0x57, 0xd3, 0x42, 0x0a, 0x2d, 0xa6, 0x89, 0xc8, 0x73, 0xc1, 0xdd, 0x4f, 0x88, 0x1c, 0xf9, 0x3d,
	0x13, 0x61, 0xce, 0x12, 0x29, 0x42, 0x25, 0x57, 0xa1, 0x2d, 0x19, 0xfe, 0x95, 0x09, 0x91, 0x2d,
	0xa9, 0x2d, 0x3b, 0x2b, 0xcf, 0xa7, 0x31, 0x5f, 0x5b, 0xfd, 0xf0, 0xae, 0x5b, 0xbc, 0x54, 0x54,
	0xd6, 0x96, 0x36, 0x10, 0x1f, 0xd7, 0x64, 0x5a, 0xa4, 0xa2, 0x26, 0x33, 0x10, 0x1f, 0x4e, 0xf6,
	0xcc, 0xc9, 0x84, 0xcc, 0x62, 0xce, 0x54, 0xac, 0x99, 0xe0, 0x35, 0x79, 0x9d, 0xde, 0x00, 0xb6,
	0x7c, 0xfc, 0xcd, 0x83, 0xee, 0x31, 0xe5, 0x29, 0xe3, 0x19, 0xd9, 0x81, 0x06, 0x4b, 0x03, 0x6f,
	0xe4, 0x4d, 0xfc, 0xa8, 0xc1, 0x52, 0xf2, 0x07, 0x74, 0x84, 0xcc, 0x16, 0x2c, 0x0d, 0x1a, 0xc8,
	0xb5, 0x85, 0xcc, 0xe6, 0x29, 0x09, 0xa0, 0x9b, 0x48, 0x1a, 0x6b, 0x9a, 0x06, 0xed, 0x91, 0x37,
	0x69, 0x46, 0x15, 0x24, 0x8f, 0xc1, 0x57, 0x17, 0xb1, 0xa4, 0xe9, 0xe2, 0x6c, 0x1d, 0x74, 0x46,
	0xde, 0xa4, 0x3f, 0xfb, 0x33, 0xdc, 0x70, 0x07, 0xf7, 0x77, 0xaa, 0xa8, 0x8c, 0x7a, 0x56, 0xf9,
	0x62, 0x4d, 0x9e, 0x42, 0xdf, 0x55, 0x7d, 0x62, 0xfa, 0x22, 0xe8, 0x6e, 0xaf, 0x03, 0xab, 0xfd,
	0xc0, 0xf4, 0x05, 0x99, 0x40, 0x8b, 0x69, 0x9a, 0x07, 0x3d, 0x2c, 0xd9, 0x0b, 0xad, 0xe7, 0x61,
	0xe5, 0x79, 0x78, 0xc8, 0xd7, 0x11, 0x2a, 0x4c, 0xcf, 0x65, 0x91, 0x62, 0xcf, 0xbe, 0xed, 0xd9,
	0xc1, 0xf1, 0xd7, 0x06, 0xec, 0x3a, 0x03, 0x22, 0xaa, 0x0a, 0xc1, 0x15, 0xbd, 0xad, 0x11, 0x7b,
	0xd0, 0x66, 0x79, 0x9c, 0xd1, 0xa0, 0x69, 0x59, 0x04, 0x86, 0xd5, 0x4c, 0x2f, 0x69, 0xd0, 0xb2,
	0x2c, 0x82, 0x2d, 0xa6, 0xdd, 0x81, 0x9d, 0xda, 0xf6, 0xcd, 0x47, 0x3a, 0x58, 0x38, 0xb8, 0xda,
	0xa8, 0x35, 0x5d, 0x95, 0x79, 0x1e, 0xcb, 0x35, 0x1a, 0xe4, 0x47, 0x15, 0xdc, 0x34, 0xbd, 0x77,
	0x5b, 0xd3, 0x2b, 0xeb, 0xfc, 0x9f, 0x5a, 0x37, 0x84, 0x5e, 0x5a, 0x4a, 0x9c, 0x99, 0x00, 0xf0,
	0xd3, 0x97, 0xd8, 0xec, 0x35, 0x11, 0x25, 0xd7, 0x41, 0x7f, 0xe4, 0x4d, 0xda, 0x91, 0x05, 0xe3,
	0xe7, 0xd0, 0x7b, 0x19, 0xaf, 0xe7, 0x9a, 0xe6, 0x8a, 0xcc, 0xa0, 0x6d, 0x56, 0x51, 0x81, 0x37,
	0x6a, 0x4e, 0xfa, 0xb3, 0xbf, 0xc3, 0x1f, 0x1c, 0x96, 0xd0, 0xa9, 0x23, 0x2b, 0x1d, 0x7f, 0x6e,
	0x42, 0xd7, 0x51, 0x37, 0xa2, 0xf8, 0x07, 0x20, 0x11, 0x5c, 0x53, 0xae, 0xaf, 0xe2, 0xf0, 0x1d,
	0x33, 0x4f, 0xc9, 0x7f, 0xd0, 0x4f, 0x62, 0x4d, 0x33, 0x21, 0xd7, 0xe6, 0xbd, 0x0d, 0x06, 0x2a,
	0x6a, 0x9e, 0x92, 0x87, 0x40, 0xae, 0x04, 0x89, 0xe0, 0x0b, 0xb5, 0x2c, 0x33, 0x17, 0xd5, 0xaf,
	0x97, 0xba, 0x44, 0xf0, 0xf7, 0xcb, 0x32, 0x23, 0xff, 0xc3, 0x2f, 0x97, 0x6a, 0x1e, 0xe7, 0x14,
	0xb3, 0xf3, 0xa3, 0x41, 0x45, 0xbe, 0x8d, 0x73, 0x8a, 0x22, 0xd7, 0x92, 0x0d, 0xde, 0xe5, 0xe7,
	0xc8, 0x13, 0xcc, 0xff, 0x1e, 0xec, 0x56, 0xa2, 0x82, 0x25, 0x8b, 0x52, 0x2e, 0x5d, 0x8e, 0x55,
	0xed, 0x31, 0x4b, 0x4e, 0xe5, 0xd2, 0xe4, 0x5c, 0x48, 0x86, 0x39, 0x9b, 0x2c, 0x7b, 0x51, 0x05,
	0x09, 0x81, 0x96, 0x66, 0x39, 0xc5, 0xc4, 0xfc, 0x08, 0xff, 0x93, 0x07, 0xd0, 0x2c, 0x24, 0xc5,
	0x58, 0x6e, 0xa4, 0x8e, 0x77, 0xc4, 0x89, 0x48, 0x45, 0x64, 0x34, 0x64, 0x1f, 0x5a, 0x85, 0x50,
	0x36, 0xa9, 0x2d, 0x5a, 0x14, 0x91, 0x27, 0xd0, 0x15, 0x85, 0x49, 0x58, 0x05, 0x83, 0x5b, 0xe4,
	0x56, 0x89, 0xc7, 0x5f, 0x3c, 0x18, 0x1e, 0x26, 0x38, 0x05, 0x47, 0x82, 0x9f, 0x33, 0x99, 0xe3,
	0x9c, 0xbc, 0xa1, 0x4a, 0x99, 0xa3, 0x71, 0x00, 0x64, 0x45, 0x25, 0x3b, 0x67, 0x09, 0xd2, 0x0b,
	0x2d, 0x3e, 0x52, 0xee, 0xc2, 0xfd, 0xad, 0xfe, 0xe6, 0xc4, 0xbc, 0x30, 0x2d, 0x9b, 0xd1, 0xc5,
	0x94, 0xb7, 0x0c, 0x35, 0x8a, 0xc8, 0x6b, 0x18, 0xd4, 0xaf, 0x37, 0x8c, 0xbe, 0x3f, 0xbb, 0xbf,
	0x59, 0xb4, 0x71, 0x01, 0xbe, 0xab, 0x81, 0x68, 0xa3, 0x78, 0xfc, 0x2f, 0x0c, 0x8e, 0xf0, 0x8a,
	0x7f, 0xc5, 0x96, 0x9a, 0xca, 0xeb, 0x53, 0x78, 0xd6, 0xc1, 0x73, 0xf2, 0xe8, 0x7b, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x39, 0xc1, 0x11, 0xd0, 0x28, 0x06, 0x00, 0x00,
}
